#!/bin/bash

echo "🚀 MianaMask Chrome Extension Setup Complete!"
echo ""
echo "📁 Project Structure:"
echo "├── manifest.json ✅"
echo "├── popup.html ✅"
echo "├── popup.js ✅"
echo "├── style.css ✅"
echo "├── ethers.js ✅"
echo "├── assets/ ✅"
echo "└── chromeapi/ (Backend) ✅"
echo ""
echo "🌐 Backend Server Status:"
curl -s http://localhost:3000/api/v1/user/test > /dev/null
if [ $? -eq 0 ]; then
    echo "✅ Backend server is running on port 3000"
else
    echo "❌ Backend server is not running. Start with: cd chromeapi && npm run start"
fi
echo ""
echo "📖 Installation Instructions:"
echo "1. Open Chrome and go to chrome://extensions/"
echo "2. Enable 'Developer mode' in the top right"
echo "3. Click 'Load unpacked' and select the /home/zahid/Downloads/mianamask folder"
echo "4. The MianaMask extension should now appear in your extensions"
echo ""
echo "🔧 Features Included:"
echo "✅ Create new wallet accounts"
echo "✅ Import existing accounts via private key"
echo "✅ Send Ethereum transactions"
echo "✅ Import custom tokens"
echo "✅ Multiple network support (Mainnet, Sepolia, Goerli, Rinkeby)"
echo "✅ Account management and switching"
echo "✅ Balance checking"
echo "✅ Transaction history"
echo "✅ Secure local storage"
echo ""
echo "🎯 Ready to test your MetaMask clone!"
